print("Edward")
print(f"Favorite color: Red\nFavorite movie: I don't Know\nFavorite song: Tenebre Rosso Sangue")
print("********\n*Edward*\n********")
print("E\nd\nw\na\nr\nd\n\nO\n\'\nB\na\nr\nr")
print(f"\"Name\"\t\"Position\"\nEdward\tFirst-Chair Viola")
animal = input("Input Animal: ")
print(f"Animal in uppercase letters: {animal.upper()}\nAnimal in lowercase letters: {animal.lower()}")
team = input("Input Sports Team: ")
print(f"First Letter: {team[0]}\nSecond Letter: {team[1]}\nThird Letter: {team[2]}")
art = input("Input Artist: ")
print(f"First and last letters: {art[0]+art[-1]}")
food = input("Favorite Food: ")
print(f"Reversed: {food[::-1]}")
sport = input("Favorite Sport: ")
print(f"Middle: {sport[1:(len(sport)-1)]}")
f_name = input("First Name: ")
m_name = input("Middle Name: ")
l_name = input("Last Name: ")
print(f"The Initials are: {f_name[0]}.{m_name[0]}.{l_name[0]}")